import type { ExerciseBlueprintsInterface } from "../interfaces/exercise.interface";

function generateRandomId(length: number = 24): string {
  const chars = "abcdef0123456789"; // Using hex characters for MongoDB-style IDs
  let result = "";
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}
// new library
// Squat exercises
export const squatExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Barbell Back Squat",
    sets: "3",
    reps: "10",
    intensity: "Barbell",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings, Calves",
    primeMovers: "Legs",
    videoUrl: "https://youtube.com/shorts/O05NSodv7tg?feature=share",
  },
  {
    _id: generateRandomId(),
    name: "Barbell Front Squat",
    sets: "3",
    reps: "10",
    intensity: "Barbell",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Core",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Barbell Overhead Squat",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Shoulders, Core",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Safety Bar Squat",
    sets: "3",
    reps: "10",
    intensity: "Safety Bar",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Safety Bar",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Upper Back",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Goblet Squat",
    sets: "3",
    reps: "12",
    intensity: "Dumbbell",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Core",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Squat",
    sets: "3",
    reps: "12",
    intensity: "Dumbbell",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Trap Bar Deadlift (squat variation)",
    sets: "3",
    reps: "8",
    intensity: "Trap Bar",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Trap Bar",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings, Lower Back",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Front Rack Kettlebell Squat",
    sets: "3",
    reps: "10",
    intensity: "Kettlebell",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Core",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Air Squat",
    sets: "3",
    reps: "15",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes",
    primeMovers: "Legs",
    videoUrl: "https://youtube.com/shorts/1not1CdzdfY?feature=share",
  },
  {
    _id: generateRandomId(),
    name: "Single-Leg Squat (Pistol Squat)",
    sets: "3",
    reps: "8",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Core, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "https://youtube.com/shorts/GIMhKWO9pLY",
  },
  {
    _id: generateRandomId(),
    name: "Box Jump",
    sets: "3",
    reps: "8",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X", // Explosive movement
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Depth Jump",
    sets: "3",
    reps: "8",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X", // Explosive movement
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Jump Squat",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X", // Explosive movement
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "https://youtube.com/shorts/TVK3RlN2FBs",
  },
  {
    _id: generateRandomId(),
    name: "Tuck Jump",
    sets: "3",
    reps: "8",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X", // Explosive movement
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hip Flexors",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Broad Jump",
    sets: "3",
    reps: "8",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X", // Explosive movement
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Split Squat Jump",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Squat",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X", // Explosive movement
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
];

// Lunge exercises
export const lungeExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Barbell Forward Lunge",
    sets: "3",
    reps: "10",
    intensity: "Barbell",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Barbell Reverse Lunge",
    sets: "3",
    reps: "10",
    intensity: "Barbell",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Lunge",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Forward Lunge",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Reverse Lunge",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Bodyweight Forward Lunge",
    sets: "3",
    reps: "12",
    intensity: "Bodyweight",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "https://youtube.com/shorts/1dDwEZx6oEk?feature=share",
  },
  {
    _id: generateRandomId(),
    name: "Bodyweight Reverse Lunge",
    sets: "3",
    reps: "12",
    intensity: "Bodyweight",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "https://youtube.com/shorts/fhWeeiPsFjg?feature=share",
  },
  {
    _id: generateRandomId(),
    name: "Box Step-Up",
    sets: "3",
    reps: "12",
    intensity: "Bodyweight",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Bulgarian Split Squat",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Lunge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Quadriceps, Glutes, Hamstrings",
    primeMovers: "Legs",
    videoUrl: "https://youtube.com/shorts/2C-uNgKwPLE",
  },
];
export const pushHorizontalExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Barbell Bench Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Chest, Triceps, Front Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Incline Barbell Bench Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Chest, Front Deltoids, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Decline Barbell Bench Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lower Chest, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Close-Grip Bench Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Triceps, Inner Chest",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Bench Press",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Chest, Triceps, Front Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Incline Dumbbell Bench Press",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Chest, Front Deltoids, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Decline Dumbbell Bench Press",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lower Chest, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Fly",
    sets: "3",
    reps: "12",
    intensity: "Dumbbell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "2-1-2",
    videoStatus: "Available",
    primaryMusclesWorked: "Chest, Front Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Push-Up",
    sets: "3",
    reps: "15",
    intensity: "Bodyweight",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Chest, Triceps, Front Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/IODxDxX7oi4",
  },
  {
    _id: generateRandomId(),
    name: "Incline Push-Up",
    sets: "3",
    reps: "15",
    intensity: "Bodyweight",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lower Chest, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/ASdvN_XEl_c",
  },
  {
    _id: generateRandomId(),
    name: "Decline Push-Up",
    sets: "3",
    reps: "12",
    intensity: "Bodyweight",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Chest, Front Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/PXIpZHsAX2E",
  },
  {
    _id: generateRandomId(),
    name: "Diamond Push-Up",
    sets: "3",
    reps: "12",
    intensity: "Bodyweight",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Triceps, Inner Chest",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/J0DnG1_S92I",
  },
  {
    _id: generateRandomId(),
    name: "Chest Dip",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lower Chest, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/vi1-BOcj3cQ",
  },
  {
    _id: generateRandomId(),
    name: "Ring Push-Up",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Rings",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Chest, Triceps, Shoulders, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Floor Press",
    sets: "3",
    reps: "10",
    intensity: "Kettlebell",
    movementPattern: "Push Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Chest, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
];

// Push Vertical exercises (pionowe pchanie)
export const pushVerticalExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Barbell Overhead Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps, Upper Chest",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Push Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-X-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps, Legs",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Seated Barbell Overhead Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps, Upper Chest",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Standing Dumbbell Shoulder Press",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Seated Dumbbell Shoulder Press",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Arnold Press",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Single-Arm Dumbbell Shoulder Press",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Press",
    sets: "3",
    reps: "10",
    intensity: "Kettlebell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Landmine Press",
    sets: "3",
    reps: "10",
    intensity: "Barbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Chest, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Pike Push-Up",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/x7_I5SUAd00",
  },
  {
    _id: generateRandomId(),
    name: "Wall Handstand Push-Up",
    sets: "3",
    reps: "8",
    intensity: "Bodyweight",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "2-1-2",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Z Press",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Push Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Triceps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
];
export const pullHorizontalExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Barbell Bent-Over Row",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Biceps, Rear Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Pendlay Row",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "T-Bar Row",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Middle Back, Lats, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Single-Arm Row",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Upper Back, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Bent-Over Row",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Seated Cable Row",
    sets: "3",
    reps: "10",
    intensity: "Cable",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Wide Grip Seated Row",
    sets: "3",
    reps: "10",
    intensity: "Cable",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Rhomboids, Rear Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Face Pull",
    sets: "3",
    reps: "12",
    intensity: "Cable",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Rear Deltoids, Upper Back, Rotator Cuff",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Inverted Row",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Biceps, Rear Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/VJaAGlQyUoQ",
  },
  {
    _id: generateRandomId(),
    name: "Ring Row",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Rings",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Biceps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Wide Grip Inverted Row",
    sets: "3",
    reps: "10",
    intensity: "Bodyweight",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Rear Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Single-Arm Inverted Row",
    sets: "3",
    reps: "8",
    intensity: "Bodyweight",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Chest Supported Row",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Rhomboids, Rear Deltoids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Meadows Row",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Upper Back, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Row",
    sets: "3",
    reps: "10",
    intensity: "Kettlebell",
    movementPattern: "Pull Horizontal",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Upper Back, Lats, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
];

// Pull Vertical exercises (pionowe ciągnięcie)
export const pullVerticalExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Pull-Up",
    sets: "3",
    reps: "6-10",
    intensity: "Bodyweight",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps, Upper Back",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/eGo4IYlbE5g",
  },
  {
    _id: generateRandomId(),
    name: "Chin-Up",
    sets: "3",
    reps: "8-12",
    intensity: "Bodyweight",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Biceps, Lats",
    primeMovers: "Upper Body",
    videoUrl: "https://youtube.com/shorts/bAEua0zu_74",
  },
  {
    _id: generateRandomId(),
    name: "Weighted Pull-Up",
    sets: "3",
    reps: "5-8",
    intensity: "Bodyweight+",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps, Upper Back",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Wide Grip Pull-Up",
    sets: "3",
    reps: "6-10",
    intensity: "Bodyweight",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Upper Back",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Neutral Grip Pull-Up",
    sets: "3",
    reps: "8-10",
    intensity: "Bodyweight",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps, Brachialis",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Commando Pull-Up",
    sets: "3",
    reps: "6-8",
    intensity: "Bodyweight",
    movementPattern: "Pull Vertical",
    plane: "Transverse",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps, Obliques",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Lat Pulldown",
    sets: "3",
    reps: "10-12",
    intensity: "Cable",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Wide Grip Lat Pulldown",
    sets: "3",
    reps: "10-12",
    intensity: "Cable",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Upper Back",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Close Grip Lat Pulldown",
    sets: "3",
    reps: "10-12",
    intensity: "Cable",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Single-Arm Lat Pulldown",
    sets: "3",
    reps: "10",
    intensity: "Cable",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Straight Arm Pulldown",
    sets: "3",
    reps: "12",
    intensity: "Cable",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Serratus Anterior",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Band Pull-Apart",
    sets: "3",
    reps: "15",
    intensity: "Band",
    movementPattern: "Pull Vertical",
    plane: "Frontal",
    type: "bilateral",
    toolsUsedInExercise: "Resistance Band",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Rear Deltoids, Rhomboids, Middle Trapezius",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Assisted Pull-Up",
    sets: "3",
    reps: "8-12",
    intensity: "Bodyweight-",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps, Upper Back",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Negative Pull-Up",
    sets: "3",
    reps: "5-8",
    intensity: "Bodyweight",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "0-0-3",
    videoStatus: "Available",
    primaryMusclesWorked: "Lats, Biceps, Upper Back",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Scapular Pull-Up",
    sets: "3",
    reps: "8-12",
    intensity: "Bodyweight",
    movementPattern: "Pull Vertical",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Lower Trapezius, Rhomboids",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
];

// HINGE exercises (zawiasy)
export const hingeExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Barbell Deadlift",
    sets: "3",
    reps: "5",
    intensity: "Barbell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Erector Spinae, Trapezius",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Sumo Deadlift",
    sets: "3",
    reps: "5",
    intensity: "Barbell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Adductors, Quadriceps, Erector Spinae",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Romanian Deadlift",
    sets: "3",
    reps: "8",
    intensity: "Barbell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "2-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Erector Spinae",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Single-Leg Romanian Deadlift",
    sets: "3",
    reps: "8-10",
    intensity: "Bodyweight",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "2-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Lower Back, Core",
    primeMovers: "Posterior Chain",
    videoUrl: "https://youtube.com/shorts/d3UhBXj8LYM",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Romanian Deadlift",
    sets: "3",
    reps: "10",
    intensity: "Dumbbell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "2-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Erector Spinae",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Dumbbell Single-Leg Romanian Deadlift",
    sets: "3",
    reps: "8",
    intensity: "Dumbbell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "2-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Core",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Good Morning",
    sets: "3",
    reps: "10",
    intensity: "Barbell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "2-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Erector Spinae",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Bodyweight Good Morning",
    sets: "3",
    reps: "15",
    intensity: "Bodyweight",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "2-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Lower Back",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Swing",
    sets: "3",
    reps: "15",
    intensity: "Kettlebell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings, Core, Delts",
    primeMovers: "Posterior Chain",
    videoUrl: "https://youtube.com/shorts/6DoD0fKnqrg",
  },
  {
    _id: generateRandomId(),
    name: "Single-Arm Kettlebell Swing",
    sets: "3",
    reps: "10-12",
    intensity: "Kettlebell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings, Core, Obliques",
    primeMovers: "Posterior Chain",
    videoUrl: "https://youtube.com/shorts/yM2UrDQVxp4",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Clean",
    sets: "3",
    reps: "8-10",
    intensity: "Kettlebell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings, Forearms, Delts",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Hip Thrust",
    sets: "3",
    reps: "12",
    intensity: "Barbell",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Bodyweight Hip Thrust",
    sets: "3",
    reps: "15",
    intensity: "Bodyweight",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings",
    primeMovers: "Posterior Chain",
    videoUrl: "https://youtube.com/shorts/BmO6AwRdFIk",
  },
  {
    _id: generateRandomId(),
    name: "Glute Bridge",
    sets: "3",
    reps: "15",
    intensity: "Bodyweight",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings",
    primeMovers: "Posterior Chain",
    videoUrl: "https://youtube.com/shorts/mmV0DZ9gVM8",
  },
  {
    _id: generateRandomId(),
    name: "Single-Leg Glute Bridge",
    sets: "3",
    reps: "12",
    intensity: "Bodyweight",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings, Core",
    primeMovers: "Posterior Chain",
    videoUrl: "https://youtube.com/shorts/cHMkuQF7a5M",
  },
  {
    _id: generateRandomId(),
    name: "Nordic Hamstring Curl",
    sets: "3",
    reps: "6-8",
    intensity: "Bodyweight",
    movementPattern: "Hinge",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "3-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
];

// CARRY exercises (noszenie)
export const carryExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Farmer's Walk",
    sets: "3",
    reps: "30-40m",
    intensity: "Dumbbell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Forearms, Traps, Core, Legs",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Farmer's Walk",
    sets: "3",
    reps: "30-40m",
    intensity: "Kettlebell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Forearms, Traps, Core, Legs",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Suitcase Carry",
    sets: "3",
    reps: "30m each side",
    intensity: "Dumbbell",
    movementPattern: "Carry",
    plane: "Frontal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Quadratus Lumborum, Core, Legs",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Suitcase Carry",
    sets: "3",
    reps: "30m each side",
    intensity: "Kettlebell",
    movementPattern: "Carry",
    plane: "Frontal",
    type: "unilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Quadratus Lumborum, Core, Legs",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Overhead Carry",
    sets: "3",
    reps: "20-30m",
    intensity: "Dumbbell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Traps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Single-Arm Overhead Carry",
    sets: "3",
    reps: "20-30m each side",
    intensity: "Dumbbell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Obliques, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Kettlebell Overhead Carry",
    sets: "3",
    reps: "20-30m",
    intensity: "Kettlebell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Traps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Waiter's Walk",
    sets: "3",
    reps: "20-30m each side",
    intensity: "Kettlebell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Core, Obliques",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Front Rack Carry",
    sets: "3",
    reps: "20-30m",
    intensity: "Kettlebell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Core, Shoulders, Upper Back",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Bottoms-Up Carry",
    sets: "3",
    reps: "15-20m each side",
    intensity: "Kettlebell",
    movementPattern: "Carry",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Kettlebells",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Forearms, Shoulders, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
];

// ROTATION/ANTI-ROTATION exercises (rotacja/anty-rotacja)
export const rotationExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Russian Twist",
    sets: "3",
    reps: "20 total",
    intensity: "Bodyweight",
    movementPattern: "Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Rectus Abdominis",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Weighted Russian Twist",
    sets: "3",
    reps: "20 total",
    intensity: "Dumbbell",
    movementPattern: "Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Dumbbell",
    tempo: "1-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Rectus Abdominis",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Cable Woodchop",
    sets: "3",
    reps: "12 each side",
    intensity: "Cable",
    movementPattern: "Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Core",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Landmine Rotation",
    sets: "3",
    reps: "10 each side",
    intensity: "Barbell",
    movementPattern: "Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Barbell",
    tempo: "1-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Core, Shoulders",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Standing Cable Rotation",
    sets: "3",
    reps: "12 each side",
    intensity: "Cable",
    movementPattern: "Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Core",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Pallof Press",
    sets: "3",
    reps: "12 each side",
    intensity: "Cable",
    movementPattern: "Anti-Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Transverse Abdominis",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Band Pallof Press",
    sets: "3",
    reps: "12 each side",
    intensity: "Band",
    movementPattern: "Anti-Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Resistance Band",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Transverse Abdominis",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Pallof Press Hold",
    sets: "3",
    reps: "20-30s each side",
    intensity: "Cable",
    movementPattern: "Anti-Rotation",
    plane: "Transverse",
    type: "bilateral",
    toolsUsedInExercise: "Cable",
    tempo: "isometric",
    videoStatus: "Available",
    primaryMusclesWorked: "Obliques, Transverse Abdominis",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Copenhagen Plank",
    sets: "3",
    reps: "20-30s each side",
    intensity: "Bodyweight",
    movementPattern: "Anti-Rotation",
    plane: "Frontal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "isometric",
    videoStatus: "Available",
    primaryMusclesWorked: "Adductors, Obliques, Quadratus Lumborum",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Bird Dog",
    sets: "3",
    reps: "10 each side",
    intensity: "Bodyweight",
    movementPattern: "Anti-Rotation",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-1-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Core, Erector Spinae, Glutes",
    primeMovers: "Core",
    videoUrl: "https://youtube.com/shorts/gVsIttw1Z5c",
  },
  {
    _id: generateRandomId(),
    name: "Dead Bug",
    sets: "3",
    reps: "10 each side",
    intensity: "Bodyweight",
    movementPattern: "Anti-Rotation",
    plane: "Sagittal",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "2-0-2",
    videoStatus: "Available",
    primaryMusclesWorked: "Transverse Abdominis, Core",
    primeMovers: "Core",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Plank Shoulder Tap",
    sets: "3",
    reps: "20 total",
    intensity: "Bodyweight",
    movementPattern: "Anti-Rotation",
    plane: "Transverse",
    type: "unilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "1-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Core, Shoulders, Obliques",
    primeMovers: "Core",
    videoUrl: "",
  },
];
export const westsideGppExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Sled Push",
    sets: "3-5",
    reps: "20-30m",
    intensity: "Sled",
    movementPattern: "GPP",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Sled",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Glutes, Calves, Core",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Sled Drag",
    sets: "3-5",
    reps: "20-30m",
    intensity: "Sled",
    movementPattern: "GPP",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Sled",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Lower Back, Core",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Backward Sled Drag",
    sets: "3",
    reps: "20m",
    intensity: "Sled",
    movementPattern: "GPP",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Sled",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Core",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Sled Pull (Rope)",
    sets: "3",
    reps: "20m",
    intensity: "Sled",
    movementPattern: "GPP",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Sled",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Back, Biceps, Core",
    primeMovers: "Upper Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Prowler Push",
    sets: "3-5",
    reps: "20-30m",
    intensity: "Prowler",
    movementPattern: "GPP",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Prowler",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Glutes, Calves, Core",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Reverse Hyper",
    sets: "3",
    reps: "15-20",
    intensity: "Machine",
    movementPattern: "GPP",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Reverse Hyper Machine",
    tempo: "1-0-1",
    videoStatus: "Available",
    primaryMusclesWorked: "Glutes, Hamstrings, Lower Back",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "GHR (Glute-Ham Raise)",
    sets: "3",
    reps: "8-12",
    intensity: "Bodyweight",
    movementPattern: "GPP",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "GHD Machine",
    tempo: "2-0-2",
    videoStatus: "Available",
    primaryMusclesWorked: "Hamstrings, Glutes, Lower Back",
    primeMovers: "Posterior Chain",
    videoUrl: "",
  },
];

// GAIT exercises (chód, bieg, rower - podstawowe formy lokomocji)
export const gaitExercises: ExerciseBlueprintsInterface[] = [
  {
    _id: generateRandomId(),
    name: "Running - Steady State",
    sets: "1",
    reps: "20-30min",
    intensity: "Bodyweight",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Calves, Core",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Running - Intervals",
    sets: "5-10",
    reps: "30s work/30s rest",
    intensity: "Bodyweight",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Calves, Core",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Running - Hill Sprints",
    sets: "5-8",
    reps: "20-30s",
    intensity: "Bodyweight",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Cycling - Steady State",
    sets: "1",
    reps: "30-45min",
    intensity: "Bike",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bike",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Cycling - Intervals",
    sets: "5-10",
    reps: "30s work/30s rest",
    intensity: "Bike",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bike",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Cycling - Hill Climbs",
    sets: "5-8",
    reps: "1-2min",
    intensity: "Bike",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bike",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Glutes",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Rowing Machine",
    sets: "1",
    reps: "20-30min",
    intensity: "Machine",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Rowing Machine",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Back, Legs, Arms, Core",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Rowing Intervals",
    sets: "5-10",
    reps: "250m",
    intensity: "Machine",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Rowing Machine",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Back, Legs, Arms, Core",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Elliptical Trainer",
    sets: "1",
    reps: "20-30min",
    intensity: "Machine",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Elliptical",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Glutes, Arms",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Stair Climber",
    sets: "1",
    reps: "15-20min",
    intensity: "Machine",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Stair Climber",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Walking",
    sets: "1",
    reps: "30-60min",
    intensity: "Bodyweight",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Incline Walking",
    sets: "1",
    reps: "20-30min",
    intensity: "Bodyweight",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Treadmill",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Quads, Hamstrings, Glutes, Calves",
    primeMovers: "Legs",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Swimming",
    sets: "1",
    reps: "20-30min",
    intensity: "Bodyweight",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Back, Shoulders, Core, Legs",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Swimming Intervals",
    sets: "5-10",
    reps: "50m",
    intensity: "Bodyweight",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Bodyweight",
    tempo: "X-X-X",
    videoStatus: "Available",
    primaryMusclesWorked: "Back, Shoulders, Core, Legs",
    primeMovers: "Full Body",
    videoUrl: "",
  },
  {
    _id: generateRandomId(),
    name: "Ski Erg",
    sets: "1",
    reps: "15-20min",
    intensity: "Machine",
    movementPattern: "Gait",
    plane: "Sagittal",
    type: "bilateral",
    toolsUsedInExercise: "Ski Erg",
    tempo: "steady",
    videoStatus: "Available",
    primaryMusclesWorked: "Shoulders, Core, Back, Legs",
    primeMovers: "Full Body",
    videoUrl: "",
  },
];

export const mockExercises = [
  ...squatExercises,
  ...lungeExercises,
  ...pushHorizontalExercises,
  ...pushVerticalExercises,
  ...pullHorizontalExercises,
  ...pullVerticalExercises,
  ...rotationExercises,
  ...carryExercises,
  ...gaitExercises,
  ...westsideGppExercises,
];

