/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as OfferImport } from './routes/offer'
import { Route as AboutmeImport } from './routes/about_me'
import { Route as IndexImport } from './routes/index'
import { Route as ContactIndexImport } from './routes/contact/index'
import { Route as ContactBasicPlanImport } from './routes/contact/basic-plan'
import { Route as ContactAthletePlanImport } from './routes/contact/athlete-plan'

// Create/Update Routes

const PortfolioRoute = PortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const OfferRoute = OfferImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRoute,
} as any)

const AboutmeRoute = AboutmeImport.update({
  id: '/about_me',
  path: '/about_me',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContactIndexRoute = ContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

const ContactBasicPlanRoute = ContactBasicPlanImport.update({
  id: '/contact/basic-plan',
  path: '/contact/basic-plan',
  getParentRoute: () => rootRoute,
} as any)

const ContactAthletePlanRoute = ContactAthletePlanImport.update({
  id: '/contact/athlete-plan',
  path: '/contact/athlete-plan',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about_me': {
      id: '/about_me'
      path: '/about_me'
      fullPath: '/about_me'
      preLoaderRoute: typeof AboutmeImport
      parentRoute: typeof rootRoute
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioImport
      parentRoute: typeof rootRoute
    }
    '/contact/athlete-plan': {
      id: '/contact/athlete-plan'
      path: '/contact/athlete-plan'
      fullPath: '/contact/athlete-plan'
      preLoaderRoute: typeof ContactAthletePlanImport
      parentRoute: typeof rootRoute
    }
    '/contact/basic-plan': {
      id: '/contact/basic-plan'
      path: '/contact/basic-plan'
      fullPath: '/contact/basic-plan'
      preLoaderRoute: typeof ContactBasicPlanImport
      parentRoute: typeof rootRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about_me': typeof AboutmeRoute
  '/offer': typeof OfferRoute
  '/portfolio': typeof PortfolioRoute
  '/contact/athlete-plan': typeof ContactAthletePlanRoute
  '/contact/basic-plan': typeof ContactBasicPlanRoute
  '/contact': typeof ContactIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about_me': typeof AboutmeRoute
  '/offer': typeof OfferRoute
  '/portfolio': typeof PortfolioRoute
  '/contact/athlete-plan': typeof ContactAthletePlanRoute
  '/contact/basic-plan': typeof ContactBasicPlanRoute
  '/contact': typeof ContactIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about_me': typeof AboutmeRoute
  '/offer': typeof OfferRoute
  '/portfolio': typeof PortfolioRoute
  '/contact/athlete-plan': typeof ContactAthletePlanRoute
  '/contact/basic-plan': typeof ContactBasicPlanRoute
  '/contact/': typeof ContactIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about_me'
    | '/offer'
    | '/portfolio'
    | '/contact/athlete-plan'
    | '/contact/basic-plan'
    | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about_me'
    | '/offer'
    | '/portfolio'
    | '/contact/athlete-plan'
    | '/contact/basic-plan'
    | '/contact'
  id:
    | '__root__'
    | '/'
    | '/about_me'
    | '/offer'
    | '/portfolio'
    | '/contact/athlete-plan'
    | '/contact/basic-plan'
    | '/contact/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutmeRoute: typeof AboutmeRoute
  OfferRoute: typeof OfferRoute
  PortfolioRoute: typeof PortfolioRoute
  ContactAthletePlanRoute: typeof ContactAthletePlanRoute
  ContactBasicPlanRoute: typeof ContactBasicPlanRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutmeRoute: AboutmeRoute,
  OfferRoute: OfferRoute,
  PortfolioRoute: PortfolioRoute,
  ContactAthletePlanRoute: ContactAthletePlanRoute,
  ContactBasicPlanRoute: ContactBasicPlanRoute,
  ContactIndexRoute: ContactIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about_me",
        "/offer",
        "/portfolio",
        "/contact/athlete-plan",
        "/contact/basic-plan",
        "/contact/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about_me": {
      "filePath": "about_me.tsx"
    },
    "/offer": {
      "filePath": "offer.tsx"
    },
    "/portfolio": {
      "filePath": "portfolio.tsx"
    },
    "/contact/athlete-plan": {
      "filePath": "contact/athlete-plan.tsx"
    },
    "/contact/basic-plan": {
      "filePath": "contact/basic-plan.tsx"
    },
    "/contact/": {
      "filePath": "contact/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
