/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OfferImport } from './routes/offer'
import { Route as AboutmeImport } from './routes/about_me'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OfferRoute = OfferImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRoute,
} as any)

const AboutmeRoute = AboutmeImport.update({
  id: '/about_me',
  path: '/about_me',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about_me': {
      id: '/about_me'
      path: '/about_me'
      fullPath: '/about_me'
      preLoaderRoute: typeof AboutmeImport
      parentRoute: typeof rootRoute
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about_me': typeof AboutmeRoute
  '/offer': typeof OfferRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about_me': typeof AboutmeRoute
  '/offer': typeof OfferRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about_me': typeof AboutmeRoute
  '/offer': typeof OfferRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about_me' | '/offer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about_me' | '/offer'
  id: '__root__' | '/' | '/about_me' | '/offer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutmeRoute: typeof AboutmeRoute
  OfferRoute: typeof OfferRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutmeRoute: AboutmeRoute,
  OfferRoute: OfferRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about_me",
        "/offer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about_me": {
      "filePath": "about_me.tsx"
    },
    "/offer": {
      "filePath": "offer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
